<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'all_produit' => [[], ['_controller' => 'App\\Controller\\ProduitController::show_all'], [], [['text', '/produits']], [], [], []],
    'create_produit' => [[], ['_controller' => 'App\\Controller\\ProduitController::create'], [], [['text', '/produits']], [], [], []],
    'get_produit' => [['id'], ['_controller' => 'App\\Controller\\ProduitController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produits']], [], [], []],
    'update_produit' => [['id'], ['_controller' => 'App\\Controller\\ProduitController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produits']], [], [], []],
    'delete_produit' => [['id'], ['_controller' => 'App\\Controller\\ProduitController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produits']], [], [], []],
    'App\Controller\ProduitController::show_all' => [[], ['_controller' => 'App\\Controller\\ProduitController::show_all'], [], [['text', '/produits']], [], [], []],
    'App\Controller\ProduitController::create' => [[], ['_controller' => 'App\\Controller\\ProduitController::create'], [], [['text', '/produits']], [], [], []],
    'App\Controller\ProduitController::show' => [['id'], ['_controller' => 'App\\Controller\\ProduitController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produits']], [], [], []],
    'App\Controller\ProduitController::update' => [['id'], ['_controller' => 'App\\Controller\\ProduitController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produits']], [], [], []],
    'App\Controller\ProduitController::delete' => [['id'], ['_controller' => 'App\\Controller\\ProduitController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produits']], [], [], []],
];
